up_compose:
	docker-compose -f docker-compose.yml up 
down_compose:
	docker-compose -f docker-compose.yml down
restart_compose:
	docker-compose -f docker-compose.yml down
	docker-compose -f docker-compose.yml up 
